# Generated by Django 5.0.3 on 2024-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_cards_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
