# Generated by Django 5.0.3 on 2024-03-11 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_publicada_cards_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='data_card',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
