# Generated by Django 5.0.3 on 2024-03-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_cards_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='publicada',
            new_name='publicado',
        ),
    ]
