# Generated by Django 5.0.3 on 2024-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_cards_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
